// Copyright 2025 Google LLC
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     https://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

// Package rust_prost implements a Rust code generator using the prost toolchain.
package rust_prost

import (
	"fmt"
	"strings"

	"github.com/googleapis/librarian/internal/license"
	"github.com/googleapis/librarian/internal/sidekick/api"
	"github.com/googleapis/librarian/internal/sidekick/parser"
	"github.com/googleapis/librarian/internal/sidekick/protobuf"
	"github.com/googleapis/librarian/internal/sidekick/rust"
)

type ExternPath struct {
	ProtoPath string
	RustPath  string
}

type modelAnnotations struct {
	CopyrightYear string
	BoilerPlate   []string
	PackageName   string
	Files         []string
	// If not empty, a segment of code to post-process the code generated by
	// Prost or Google-protobuf.
	PostProcessProtos []string
	ExternPaths       []ExternPath
}

type serviceAnnotations struct {
	ID string
}

type methodAnnotations struct {
	ID string
}

func (codec *codec) annotateModel(model *api.API, cfg *parser.ModelConfig) error {
	rootSource := cfg.Source.Root(codec.RootName)
	files, err := protobuf.DetermineInputFiles(cfg.SpecificationSource, cfg.Source)
	if err != nil {
		return err
	}
	for i, f := range files {
		files[i] = strings.TrimPrefix(f, rootSource+"/")
	}
	packageName := rust.PackageName(model, codec.PackageName)
	var externPaths []ExternPath
	if packageName != "google-cloud-rpc" {
		externPaths = append(externPaths, ExternPath{
			ProtoPath: ".google.rpc",
			RustPath:  "::google_cloud_rpc::prost",
		})
	}
	if packageName != "google-cloud-longrunning" {
		externPaths = append(externPaths, ExternPath{
			ProtoPath: ".google.longrunning",
			RustPath:  "::google_cloud_longrunning::prost",
		})
	}
	annotations := &modelAnnotations{
		CopyrightYear: codec.GenerationYear,
		BoilerPlate: append(license.HeaderBulk(),
			"",
			" Code generated by sidekick. DO NOT EDIT."),
		PackageName:       packageName,
		Files:             files,
		PostProcessProtos: codec.PostProcessProtos,
		ExternPaths:       externPaths,
	}
	fmt.Printf("DEBUG: Package %q, resolved Files: %v\n", annotations.PackageName, annotations.Files)
	for _, s := range model.Services {
		codec.annotateService(s)
	}
	model.Codec = annotations
	return nil
}

func (codec *codec) annotateService(service *api.Service) {
	annotations := &serviceAnnotations{
		ID: strings.TrimPrefix(service.ID, "."),
	}
	for _, method := range service.Methods {
		codec.annotateMethod(method)
	}
	service.Codec = annotations
}

func (codec *codec) annotateMethod(method *api.Method) {
	annotations := &methodAnnotations{
		ID: strings.TrimPrefix(method.ID, "."),
	}
	method.Codec = annotations
}
